### ISSUE TITLE
'J' character added to print jobs and new lines

### ISSUE THREAD

**Issue by dlbfleet** [adafruit/Adafruit_CircuitPython_Thermal_Printer#23]
When using the import stack called for in the tutorial, the uppercase letter 'J' is added before a new sequence of character or lines is written.

This will print a 'J' before the text:

`import serial
uart = serial.Serial("/dev/serial0", baudrate=19200, timeout=3000)
import adafruit_thermal_printer
ThermalPrinter = adafruit_thermal_printer.get_printer_class(2.16)
printer = ThermalPrinter(uart)

printer.print("____IIII_____\nhi hi\n")`

This will print a 'J'  before the newlines:

`import serial
uart = serial.Serial("/dev/serial0", baudrate=19200, timeout=3000)
import adafruit_thermal_printer
ThermalPrinter = adafruit_thermal_printer.get_printer_class(2.16)
printer = ThermalPrinter(uart)

printer.feed(8)`

I am using:
Raspberry Pi 4, with RPi OS updated a few days ago
Normal size thermal printer (Model CSN-A2)
SelfTest tells me version 2.16.08, which throws an error in __init__, so I use 2.16, which calls thermal_printer_legacy.

Looking at the function calls and inspecting with print statements, these prints happen after ThermalPrinter.write_char is called. I.E. - if I tell it to write a character at the end of the function, the J is not printed yet, and will overwrite whatever character I have it print.

Also, it's worth noting, that using a higher version number like 2.17, that calls the other class, does not result in this problem.

**Comment by greg-elmi** [comment]
@dlbfleet Vesrion of printer firmware 2.16.08 should be called as 2.168 in this library as per [this](https://github.com/adafruit/Adafruit_CircuitPython_Thermal_Printer/pull/20) merge.

Library call 2.16 corresponds to 2.1.06 version of printer's firmware.

I know it is a little confusion but I had no other idea how to call it while preserving backward compatibility.

This issue is a copy of [#18 ](https://github.com/adafruit/Adafruit_CircuitPython_Thermal_Printer/issues/18) issue

**Comment by caternuson** [comment]
@dlbfleet Is this fixed now with the updates mentioned above?

**Comment by rimwolf-redux** [comment]
Seems like it would be useful to have `get_printer_class` accept the same string that selftest prints out.

**Comment by tekktrik** [comment]
Closing because the duplicate issue was closed and no response
